name: Nest Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - name: Run tests
        run: npm test
        run: run build
